exclude: ^({{cookiecutter.project_slug}})
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-docstring-first
          - id: check-yaml
          - id: check-json
          - id: debug-statements
          - id: name-tests-test
          - id: requirements-txt-fixer
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            args: [-l, "79"]
    - repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.31.1
      hooks:
          - id: pyupgrade
            args: [--py37-plus]
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.0.1
      hooks:
          - id: reorder-python-imports
            args: [--py37-plus]
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.2.2
      hooks:
          - id: add-trailing-comma
            args: [--py36-plus]
    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: v1.20.1
      hooks:
          - id: setup-cfg-fmt
